### ISSUE TITLE
Problems with calling curl_global_cleanup

### ISSUE THREAD

**Issue by iamed2** [invenia/FTPClient.jl#1]
Several libraries call libcurl's `curl_global_cleanup`. Once it is called in one library, the others will not be usable until they call `curl_global_init` again! This will get even worse with threading.

Options:
1) Ensure no libraries ever call cleanup (might be okay but we can't be sure whether new libraries will obey this)
2) Have some sort of semaphore built into the LibCURL.jl package itself. Dunno if that even can be done in a threadsafe manner (can be done before threading obviously). 
3) Reimplement the library using TcpSockets, seems not too hard actually: https://hg.python.org/cpython/file/2.7/Lib/ftplib.py

**Comment by iamed2** [comment]
http://blog.leahhanson.us/using-tcp-sockets-in-julia.html

**Comment by omus** [comment]
Issue may not be as bad as it first appeared:

http://curl.haxx.se/libcurl/c/libcurl.html#GLOBAL
http://curl.haxx.se/libcurl/c/libcurl-tutorial.html (See Multi-threading Issues)

**Comment by iamed2** [comment]
@omus this might be causing the segfaults that occur when coverage is turned on in tests. Removing the cleanup causes the segfaults to go away.

**Comment by samuel-massinon** [comment]
Doesn't seem to be an issue.
