### ISSUE TITLE
OS X java runtime is not present

### ISSUE THREAD

**Issue by samuel-massinon** [invenia/FTPClient.jl#18]
The [last build on OS X](https://travis-ci.org/invenia/FTPClient.jl/jobs/97065956) failed because 

```
No Java runtime present, requesting install.
```

[JavaCall.jl](https://github.com/aviks/JavaCall.jl) has the same [issue](https://travis-ci.org/aviks/JavaCall.jl/jobs/84890628)

I removed OS X from the os builds in travis.

**Comment by omus** [comment]
Switch away from JavaCall.jl should make this no longer an issue.
