### ISSUE TITLE
use environment variable for SSL

### ISSUE THREAD

**Issue by nick-thiessen** [invenia/FTPClient.jl#64]
Would be nice if FTPClient checked an environment variable on whether or not to use SSL for FTP.

**Comment by omus** [comment]
Although URI login options are not supported out of the box by LibCURL we be able to use this syntax for explicit SSL: `ftp://user:password;ssl=true@ftp.example.com/`.

For details see the [CURLOPT_URL documentation](https://curl.haxx.se/libcurl/c/CURLOPT_URL.html)
