### ISSUE TITLE
Inconsistencies with `upload` interface

### ISSUE THREAD

**Issue by omus** [invenia/FTPClient.jl#73]
When attempting to do `upload.(Ref(ftp), files, Ref("/"))` the call failed with `ERROR: Failed to upload /. :: LibCURL error #3`. Upon investigating it appears that the `upload(ftp, file, "/")` method does not use the `basename` of the local file and just tries to write to the file `"/"`. However if you use `upload(ftp, files, "/")` things work as you would expect. The inconsistencies here should be addressed.

**Comment by fchorney** [comment]
This was fixed in #79 Closing.
